/* 
  cance
*/

export const dataOrders = [
  {
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 2,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 2,
    "status" : 1,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 3,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 1,
    "status" : 3,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 4,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 8,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 5,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },{
    "idOrder" : 1,
    "nameClient": "Luismiguel Ortiz Alvarez",
    "destinationCity" : "Delicias , Chihuahua",
    "total" : "3302.36",
    "paymentMethod": 0,
    "status" : 0,
    "date" : new Date(),
    "noProducts" : 2,
  },
]
